version: '3.4'

services:
  db:
    container_name: systems-design-app-db
    image: postgres
    restart: unless-stopped
    environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports: 
        - "5432:5432"

  pgadmin:
    container_name: systems-design-app-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports: 
        - "5050:80"